package constant

const (
	// AuthAdmin ...
	AuthAdmin = "admin"
	// AuthMember ...
	AuthMember = "member"
)
const (
	// PermissionGet ...
	PermissionGet = "get"
	// PermissionUpdate ...
	PermissionUpdate = "update"
	// PermissionList ...
	PermissionList = "list"
	// PermissionCreate ...
	PermissionCreate = "create"
	// PermissionDelete ...
	PermissionDelete = "delete"
	// PermissionAll ...
	PermissionAll = "all"
)

const (
	// OperationCreate ...
	OperationCreate = "create"
	// OperationDelete ...
	OperationDelete = "delete"
)
