openapi: 3.0.0
info:
  description: Urbs 灰度平台管控后台应用
  version: 0.8.0
  title: urbs-console
servers:
  - url: http://urbs-console:8080
    description: 这是内部服务，请替换为实际 URL
tags:
  - name: Version
    description: 获取 urbs-console 服务版本信息
  - name: User
    description: User 用户相关接口
components:
  parameters:
    HeaderAuthorization:
      in: header
      name: Authorization
      description: '用户 Token, 格式如: `Bearer xxx`；header 不存在，尝试从 cookie 中读取'
      required: true
      schema:
        type: string
    HeaderAuthorizationService:
      in: header
      name: Authorization
      description: 'JWT Token, 格式如: `Bearer xxx`'
      required: true
      schema:
        type: string
    HeaderAuthorizationOpenTrust:
      in: header
      name: Authorization
      description: 'OTVID, 格式如: `Bearer OTVID`'
      required: true
      schema:
        type: string
    QueryProduct:
      in: query
      name: product
      description: 产品名称
      required: true
      schema:
        type: string
    QueryPageSize:
      in: query
      name: pageSize
      description: 分页大小，默认为 10，(1-1000]
      required: false
      schema:
        type: integer
        format: int32
        default: 10
        example: 20
    QueryPageToken:
      in: query
      name: pageToken
      description: 分页请求标记，来自于响应结果的 nextPageToken
      required: false
      schema:
        title: pageToken
        type: string
        default: ""
        example: "2020-03-13T11%3A59%3A48Z"
    QueryQ:
      in: query
      name: q
      description: 部分列表类 API 支持搜索，q 为搜索关键词
      required: false
      schema:
        title: q
        type: string
        default: ""
    PathProduct:
      in: path
      name: product
      description: 产品名称
      required: true
      schema:
        type: string
  schemas:
    NextPageToken:
      title: nextPageToken
      type: string
      description: 用于分页查询时用于获取下一页数据的 token，当为空值时表示没有下一页了
      example: ""
    TotalSize:
      title: totalSize
      type: integer
      format: int64
      description: 当前分页查询的总数据量
      example: 1
    Version:
      type: object
      properties:
        name:
          type: string
          description: 服务名称
          example: urbs-console
        version:
          type: string
          description: 当前版本
          example: v1.2.0
        gitSHA1:
          type: string
          description: git commit hash
          example: cd7e82a
        buildTime:
          type: string
          format: date-time
          description: 打包构建时间
          example: 2020-03-25T06:24:25Z
    MySetting:
      type: object
      properties:
        hid:
          type: string
          description: 配置项的 hid
          example: AwAAAAAAAAB25V_QnbhCuRwF
        product:
          type: string
          description: 配置项所属的产品名称
          example: teambition
        module:
          type: string
          description: 配置项所属的功能模块名称
          example: task
        name:
          type: string
          description: 配置项名称
          example: task-share
        value:
          type: string
          description: 配置项值
          example: disable
        assignedAt:
          type: string
          format: date-time
          description: 配置项被设置时间
          example: 2020-03-25T06:24:25Z
    MyLabel:
      type: object
      properties:
        hid:
          type: string
          description: 标签的 hid
          example: AwAAAAAAAAB25V_QnbhCuRwF
        product:
          type: string
          description: 标签所属的产品名称
          example: teambition
        name:
          type: string
          description: 标签名称
          example: gray
        assignedAt:
          type: string
          format: date-time
          description: 标签被设置时间
          example: 2020-03-25T06:24:25Z   
  requestBodies:          
    ApplyRulesBody:
      required: true
      description: 触发用户应用规则
      content:
        application/json:
          schema:
            type: object
            properties:
              users:
                type: array
                description: 用户 uid 数组，必须符合正则 /^[0-9A-Za-z._=-]{3,63}$/
                required: true
                example: ["50c32afae8cf1439d35a87e6", "5e69a9bd6ac3cd00213ea969"]
                items:
                  type: string
              kind:
                type: string
                description: 规则类型
                example: newUserPercent 
  responses:
    MySettingsRes:
      description: 用户或群组被指派的配置项列表返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              nextPageToken:
                $ref: "#/components/schemas/NextPageToken"
              result:
                type: array
                items:
                  $ref: "#/components/schemas/MySetting"
    MyLabelsRes:
      description: 用户或群组被指派的标签列表返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              nextPageToken:
                $ref: "#/components/schemas/NextPageToken"
              result:
                type: array
                items:
                  $ref: "#/components/schemas/MyLabel"
    BoolRes:
      description: 标准 Boolean 类返回结果
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: boolean
                description: 是否成功
                example: true
    Version:
      description: version 返回结果
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Version"                 
paths: