openapi: 3.0.0
info:
  description: Urbs 灰度平台管控后台应用
  version: 0.1.0
  title: urbs-console
servers:
  - url: http://urbs-console:8080
    description: 这是内部服务，请替换为实际 URL
tags:
  - name: Version
    description: 获取 urbs-console 服务版本信息
  - name: User
    description: User 用户相关接口
components:
  schemas:
    NextPageToken:
      title: nextPageToken
      type: string
      description: 用于分页查询时用于获取下一页数据的 token，当为空值时表示没有下一页了
      example: "hid.fog-AAAAAABWPxcs-4UJ3Aw9"
    TotalSize:
      title: totalSize
      type: integer
      format: int64
      description: 当前分页查询的总数据量
      example: 99
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: 错误代号
          example: NotFound
        message:
          type: string
          description: 错误详情
          example: user 50c32afae8cf1439d35a87e6 not found
    BoolRes:
      type: object
      properties:
        result:
          type: boolean
          description: 是否成功
          example: true
    Version:
      type: object
      properties:
        name:
          type: string
          description: 服务名称
          example: urbs-setting
        version:
          type: string
          description: 当前版本
          example: v0.1.0
        gitSHA1:
          type: string
          description: git commit hash
          example: cd7e82a
        buildTime:
          type: string
          format: date-time
          description: 打包构建时间
          example: 2020-03-25T06:24:25Z
    MySettingsRes:
      type: object
      properties:
        totalSize:
          $ref: "#/components/schemas/TotalSize"
        nextPageToken:
          $ref: "#/components/schemas/NextPageToken"
        result:
          type: array
          items:
            $ref: "#/components/schemas/MySetting"
    MySetting:
      type: object
      properties:
        hid:
          type: string
          description: 灰度标签的 HID
          example: AwAAAAAAAAB25V_QnbhCuRwF
        module:
          type: string
          description: 产品模块名称
          example: teambition
        name:
          type: string
          description: 模块配置名称
          example: beta
        value:
          type: string
          description: 模块配置的值
        last_value:
          type: string
          description: 上次模块配置的值
        created_at:
          type: string
          format: date-time
          description: 创建时间
          example: 2020-03-25T06:24:25Z
        updated_at:
          type: string
          format: date-time
          description: 更新时间
          example: 2020-03-25T06:24:25Z
paths:
  /version:
    get:
      tags:
        - Version
      summary: 获取版本信息
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'