addr: ":8080"
tls:
    cert_path: ""
    key_path: ""
urbs_setting:
    addr: ""
    auth_keys: ["a29b3a29b3a29b30x1a29b38"]   
logger:
    level: "info"
thrid:
    key: "a29b3a29b3a29b30x1a29b38"
    user_auth: 
        url: ""
        cookie_keys: []
    group_member: 
        url: ""