addr: ":8080"
tls:
    cert_path: ""
    key_path: ""
urbs_setting:
    addr: "http://127.0.0.1:8081"
    key: "a29b3a29b3a29b30x1a29b38"
logger:
    level: "info"
thrid:
    key: "a29b3a29b3a29b30x1a29b38"
    user_auth: 
        url: ""
        cookie_key: ""
    group_member: 
        url: ""