addr: ":8080"
tls:
    cert_path: ""
    key_path: ""
urbs_setting:
    addr: "mock"
    key: "a29b3a29b3a29b30x1a29b38"
logger:
    level: "debug"
thrid:
    key: "a29b3a29b3a29b30x1a29b38"
    user_auth: 
        url: "mock"
        cookie_key: ""
    group_member: 
        url: ""
    hook: 
        url: ""
        events: ["setting.offline"]
mysql:
    host: localhost:3306
    user: root
    password: password
    database: urbs_console
    parameters: loc=UTC&readTimeout=10s&writeTimeout=10s&timeout=10s&multiStatements=true
    max_idle_conns: 8
    max_open_conns: 64
superAdmins: []
auth_keys:
    - kqGuLsiKT1J5ANFDKXUHc2lAYfdzWBnriL1iHgBbYQ